server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        #换成VM202上的nginx端口1111，做集群
        server-addr: 192.168.234.202:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'